pipeline {
    agent any
    parameters{
    choice(
        name:'ACTION',
        choices:['apply','destroy'],
        description:'Select Terraform action'
        )
     }

    stages {

        stage('terraform init') {
            steps {
            
            sh 'terraform init'
          
       }
    }
        stage('terraform plan') {
            steps {
               
               sh 'terraform plan'
            
        }
    }
        stage('terraform apply/destroy') {
            steps {
                
               sh 'terraform ${ACTION} -auto-approve'
            
          }
        }
     }
   }


